version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.code.findbugs:annotations
    versions:
    - "> 3.0.1, < 3.1"
  - dependency-name: com.commercetools.sdk.jvm.core:commercetools-convenience
    versions:
    - 1.60.0
    - 1.61.0
  - dependency-name: com.commercetools.sdk.jvm.core:commercetools-java-client-ahc-2_5
    versions:
    - 1.61.0
  - dependency-name: com.commercetools.sdk.jvm.core:commercetools-models
    versions:
    - 1.60.0
    - 1.61.0
  - dependency-name: com.commercetools.sdk.jvm.core:commercetools-java-client
    versions:
    - 1.60.0
  - dependency-name: org.mockito:mockito-junit-jupiter
    versions:
    - 3.8.0
  - dependency-name: com.github.spotbugs
    versions:
    - 4.6.2
  - dependency-name: com.diffplug.spotless
    versions:
    - 5.10.0
    - 5.10.1
    - 5.10.2
  - dependency-name: org.junit.vintage:junit-vintage-engine
    versions:
    - 5.7.1
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.1
  - dependency-name: org.junit.jupiter:junit-jupiter-params
    versions:
    - 5.7.1
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.1
