name: CD

on:
  push:
    branches:
      - test_deployment

jobs:
  deployment:
    name: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
      - name: status
        run: echo Build is tagged. Uploading artifact ${{ steps.vars.outputs.tag }} to maven central.
      - name: Publish GitHub Pages
        run: ./gradlew --info -Dbuild.version="${{ steps.vars.outputs.tag }}" mkdocsPublish
