name: CD

on:
  push:
    branches:
      - test_deployment

jobs:
  deployment:
    name: deployment
    runs-on: ubuntu-latest
    env:
      GRGIT_USER: ${{ secrets.GRGIT_USER }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
      - name: status
        run: echo Build is tagged. Uploading artifact ${{ steps.vars.outputs.tag }} to maven central.
      - name: Publish GitHub Pages
        run: ./gradlew --info -Dbuild.version="${{ steps.vars.outputs.tag }}" mkdocsPublish
