name: CD

on: [push]

jobs:
  benchmark_tests:
    name: benchmark tests
    runs-on: ubuntu-latest
    env:
      SOURCE_PROJECT_KEY: java-sync-target-dev2
      SOURCE_CLIENT_ID: ${{ secrets.TARGET_CLIENT_ID_2 }}
      SOURCE_CLIENT_SECRET: ${{ secrets.TARGET_CLIENT_SECRET_2 }}
      TARGET_PROJECT_KEY: java-sync-target-dev2
      TARGET_CLIENT_ID: ${{ secrets.TARGET_CLIENT_ID_2 }}
      TARGET_CLIENT_SECRET: ${{ secrets.TARGET_CLIENT_SECRET_2 }}
      GRGIT_USER: ${{ secrets.GRGIT_USER }}
      GITHUB_ACTION_COMMIT: ${{github.sha}}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: serializing workflow runs
        uses: softprops/turnstyle@v1
        with:
          same-branch-only: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch Library version
        id: vars
        run: echo ::set-output name=libVersion::${GITHUB_REF#refs/*/}
      - name: benchmark test
        if: ${{ success() }}
        run: ./gradlew clean setLibraryVersion benchmark benchmarkCommit
        env:
          GITHUB_TAG: ${{ steps.vars.outputs.libVersion }}
