name: CD

on:
  push:
    tags:
      - '*.*.*'

jobs:
  benchmark_tests:
    name: benchmark tests
    concurrency: benchmark_tests
    runs-on: ubuntu-latest
    env:
      SOURCE_PROJECT_KEY: java-sync-target-dev2
      SOURCE_CLIENT_ID: ${{ secrets.TARGET_CLIENT_ID_2 }}
      SOURCE_CLIENT_SECRET: ${{ secrets.TARGET_CLIENT_SECRET_2 }}
      TARGET_PROJECT_KEY: java-sync-target-dev2
      TARGET_CLIENT_ID: ${{ secrets.TARGET_CLIENT_ID_2 }}
      TARGET_CLIENT_SECRET: ${{ secrets.TARGET_CLIENT_SECRET_2 }}
      GRGIT_USER: ${{ secrets.GRGIT_USER }}
      SUBMIT_BENCHMARK_RESULT: true
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: benchmark test
        if: ${{ success() }}
        run: ./gradlew -Dbuild.version="${{ github.ref_name }}" clean benchmark
        env:
          GITHUB_TAG: ${{ github.ref_name }}
  deployment:
    name: deployment
    needs: benchmark_tests
    runs-on: ubuntu-latest
    env:
      GRGIT_USER: ${{ secrets.GRGIT_USER }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
      - name: status
        run: echo Build is tagged. Uploading artifact ${{ github.ref_name }} to maven central.
      - name: Publish GitHub Pages
        run: ./gradlew --info -Dbuild.version="${{ github.ref_name }}" mkdocsPublish
      - name: deploy to sonatype and publish to maven central
        run: ./gradlew -Dbuild.version="${{ github.ref_name }}" publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          GITHUB_TAG: ${{ github.ref_name }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          PGP_KEY: ${{ secrets.PGP_KEY }}
          PGP_PASSWORD: ${{ secrets.PGP_PASSWORD }}
      - name: Slack notification
        if: success() # only when previous step succeeds
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Github Release Action.
          SLACK_CHANNEL: java-sync
        uses: Ilshidur/action-slack@master
        with:
          args: 'Version: <https://github.com/commercetools/commercetools-sync-java/releases/tag/${{ steps.vars.outputs.tag }}|${{ steps.vars.outputs.tag }}> of the library has been published to the <https://repo1.maven.org/maven2/com/commercetools/commercetools-sync-java/|Maven Central>.'
