name: CD

on:
  push:
    tags:
      - '*.*.*'

jobs:
  benchmark_tests:
    name: benchmark tests
    runs-on: ubuntu-latest
    env:
      SOURCE_PROJECT_KEY: java-sync-target-dev2
      SOURCE_CLIENT_ID: ${{ secrets.TARGET_CLIENT_ID_2 }}
      SOURCE_CLIENT_SECRET: ${{ secrets.TARGET_CLIENT_SECRET_2 }}
      TARGET_PROJECT_KEY: java-sync-target-dev2
      TARGET_CLIENT_ID: ${{ secrets.TARGET_CLIENT_ID_2 }}
      TARGET_CLIENT_SECRET: ${{ secrets.TARGET_CLIENT_SECRET_2 }}
      CI_BUILD_DIR: '/home/runner/work/commercetools-sync-java/commercetools-sync-java/'
      GRGIT_USER: ${{ secrets.GRGIT_USER }}
      GITHUB_ACTION_COMMIT: ${{github.sha}}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: serializing workflow runs
        uses: softprops/turnstyle@v1
        with:
          same-branch-only: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch Library version
        id: vars
        run: echo ::set-output name=libVersion::${GITHUB_REF#refs/*/}
      - name: benchmark test
        if: ${{ success() }}
        run: ./gradlew clean setLibraryVersion benchmark benchmarkCommit
        env:
          GITHUB_TAG: ${{ steps.vars.outputs.libVersion }}

  deployment:
    name: deployment
    needs: benchmark_tests
    runs-on: ubuntu-latest
    env:
      GRGIT_USER: ${{ secrets.GRGIT_USER }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: status
        run: echo Build is tagged. Uploading artifact ${{ steps.vars.outputs.tag }} to maven central.
      - name: Publish GitHub Pages
        run: ./gradlew --info -Dbuild.version="${{ steps.vars.outputs.tag }}" mkdocsPublish
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: deploy to sonatype
        run: ./gradlew setLibraryVersion -Dbuild.version="${{ steps.vars.outputs.tag }}" publish
        env:
          GITHUB_TAG: ${{ steps.vars.outputs.tag }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          PGP_KEY: ${{ secrets.PGP_KEY }}
          PGP_PASSWORD: ${{ secrets.PGP_PASSWORD }}
      - name: release to maven Central
        run: ./gradlew closeAndReleaseRepository
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - name: Slack notification
        if: success() # only when previous step succeeds
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Github Release Action.
          SLACK_CHANNEL: java-sync
        uses: Ilshidur/action-slack@master
        with:
          args: 'Version: <https://github.com/commercetools/commercetools-sync-java/releases/tag/${{ steps.vars
          .outputs.tag }}|${{ steps.vars.outputs.tag }}> of the library is published to the  <https://oss.sonatype.org/|nexus repository manager>, check <https://github.com/commercetools/commercetools-sync-java/blob/master/docs/BUILD.md#step-3-publish-to-maven-central|here> for the next steps.'
