name: CI

on: [push]

jobs:
  tests:
    name: Tests
    concurrency: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Build with Gradle
        run: ./gradlew clean integrationTest --tests com.commercetools.sync.integration.sdk2.ctpprojectsource.customers.CustomerSyncIT
        env:
          SOURCE_PROJECT_KEY: java-sync-source
          SOURCE_CLIENT_ID:  ${{ secrets.SOURCE_CLIENT_ID }}
          SOURCE_CLIENT_SECRET:  ${{ secrets.SOURCE_CLIENT_SECRET }}
          TARGET_PROJECT_KEY: java-sync-target
          TARGET_CLIENT_ID: ${{ secrets.TARGET_CLIENT_ID }}
          TARGET_CLIENT_SECRET: ${{ secrets.TARGET_CLIENT_SECRET }}
      - name: Codecov
        uses: codecov/codecov-action@v3
