name: CI

on: [push]

jobs:
  checks:
    name: Code Checks
    runs-on: ubuntu-latest
    steps:
      - name: Slack notification
          if: success() # only when previous step succeeds
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_USERNAME: Github Release Action.
            SLACK_CHANNEL: java-sync
          uses: Ilshidur/action-slack@master
          with:
            args: 'Version: <http://www.google.de|google> of the library is released to bintray'
